name: CICD Builds

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - name: Build
        run: dotnet build --configuration Release /p:Version=${VERSION}
      - name: Test
        run: dotnet test --configuration Release --no-build /p:Version=${VERSION}
      - name: Package
        run: dotnet pack --configuration Release --no-build /p:Version=${VERSION} --output .
      - name: Publish to ghcr.io nuget repo
        run: dotnet nuget push ./WiegandTech.JetNet.${VERSION}.nupkg --source github --api-key "$TOKEN" --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to nuget.org
        run: dotnet nuget push ./WiegandTech.JetNet.${VERSION}.nupkg --source nuget.org --api-key "$TOKEN" --source https://api.nuget.org/v3/index.json
        env:
          TOKEN: ${{ secrets.NUGET_TOKEN }}

